
###  GET request someDataFromReader
GET localhost:8080/actuator/health

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###  GET request someDataFromReader
GET localhost:8080/actuator/mem

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###  GET request someDataFromReader
GET localhost:8080/actuator/config

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}