

###  GET request graphql
GET localhost:8080/graphql/

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###  POST request
POST localhost:8080/graphql/query
Content-Type: application/json;charset=UTF-8

{"query":"query findTodos {\n  todos {\n    text\n    done\n    id\n    user {\n      id\n      name\n    }\n  }\n}","operationName":"findTodos"}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}