

###  GET request ping
GET localhost:8080/restapi/ping
###  GET request json / return unicode and content-length is longer
GET localhost:8080/restapi/json
###  GET request purejson
GET localhost:8080/restapi/purejson
###  POST request
POST localhost:8080/restapi/post?id=123&page5
Content-Type: application/x-www-form-urlencoded

name=John Doe&message=is hungry
###  GET request someDataFromReader
GET localhost:8080/restapi/someDataFromReader
###  GET request someJSON2
GET localhost:8080/restapi/someJSON2
###  GET request with path variable
GET localhost:8080/restapi/thinkerou/987fbc97-4bed-5078-9f07-9141ba07c9f3
###  GET request someXML
GET localhost:8080/restapi/someXML
###  GET request someYAML
GET localhost:8080/restapi/someYAML
###  GET request someJSON
GET localhost:8080/restapi/someJSON
###  GET request moreJSON
GET localhost:8080/restapi/moreJSON
