server:
  portNumber: 8080

oauth2:
  redirectUrl:  "http://localhost:8080/login/oauth2/code/dbwebsso",
  clientId: ${CLIENT_ID}
  clientSecret: ${CLIENT_SECRET}
  scopes:
    - "54f98af6-5da1-4d54-8610-8fad122aa628/.default"
    - "openid"
    - "profile"
    - "email"
  endPoint: "a1a72d9c-49e6-4f6d-9af6-5aafa1183bfd"
